name: gateapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_html: ^0.11.0
  url_launcher: ^5.1.4
  geolocator: ^5.1.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intro_slider: ^2.2.8
  provider: 3.1.0
  intl: 0.16.0
  dio: 2.1.16
  material_design_icons_flutter: 3.2.4096
  flutter_screenutil: ^0.5.3
  validators: ^2.0.0+1
  qrcode_reader: ^0.4.4
  share: ^0.6.2+4
  flutter_share: ^1.0.2+1
  esys_flutter_share: 1.0.2
  wc_flutter_share: 0.1.1
  #image_picker: ^0.6.1+8
  http: ^0.12.0+2
  # qr_mobile_vision: ^0.2.2
  progress_dialog: ^1.2.0
  flushbar: 1.9.0
  shared_preferences: ^0.4.3
  flutter_udid: 1.0.0
  # image_picker_modern: ^0.4.12+3
  #permission_handler: '^1.0.1'
  image_picker:
    path: ./image_picker

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/gateman/
    - assets/gateman_spinner.gif

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
